FROM quay.io/fedora/fedora-coreos:stable

LABEL org.opencontainers.image.title="Fedora CoreOS"
LABEL org.opencontainers.image.description="Fedora CoreOS UKI"
LABEL org.opencontainers.image.source="https://github.com/travier/fedora-coreos-uki"
LABEL org.opencontainers.image.licenses="MIT"

# RUN rpm-ostree install dnf
RUN install -dm 0755 -o 0 -g 0 /usr/lib/ostree \
    && \
    echo -n "[composefs]\nenabled = yes\n" > /usr/lib/ostree/prepare-root.conf

RUN ostree container commit
