FROM quay.io/fedora/fedora-coreos:stable

LABEL org.opencontainers.image.title="Fedora CoreOS"
LABEL org.opencontainers.image.description="Fedora CoreOS UKI"
LABEL org.opencontainers.image.source="https://github.com/travier/fedora-coreos-uki"
LABEL org.opencontainers.image.licenses="MIT"

# Install the required tools
RUN rpm-ostree install \
        sbsigntools \
        systemd-boot-unsigned \
        systemd-ukify

# Setup composefs for signed mode
RUN install -dm 0755 -o 0 -g 0 /usr/lib/ostree && \
    echo -n "[composefs]\nenabled=signed\n" > /usr/lib/ostree/prepare-root.conf

# Import ostree commit signing public key
ADD ostree-sign.pub /etc/ostree/initramfs-root-binding.key

# Regenerate the initrd using dracut
RUN export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    stock_arguments=$(lsinitrd "/lib/modules/${KERNEL_VERSION}/initramfs.img"  | grep '^Arguments: ' | sed 's/^Arguments: //') && \
    mkdir -p /tmp/dracut /var/roothome && \
    bash <(/usr/bin/echo "dracut $stock_arguments") && \
    rm -rf /var/* /tmp/*  && \
    mv -v /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img"

# Generate UKI & sign it for Secure Boot
RUN --mount=type=secret,id=key \
    --mount=type=secret,id=cert \
    export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    ukify build \
        --linux "/usr/lib/modules/${KERNEL_VERSION}/vmlinuz" \
        --initrd "/usr/lib/modules/${KERNEL_VERSION}/initramfs.img" \
        --cmdline "mitigations=auto,nosmt ignition.platform.id=qemu console=tty0 console=ttyS0,115200n8 ignition.firstboot" \
        --os-release "/etc/os-release" \
        --signtool sbsign \
        --secureboot-private-key "/run/secrets/key" \
        --secureboot-certificate "/run/secrets/cert" \
        --output "/usr/lib/modules/${KERNEL_VERSION}/uki" \
        --measure \
        --json pretty

# Remove now unneeded kernel & initramfs
RUN rm -vf /usr/lib/modules/*/vmlinuz /usr/lib/modules/*/initramfs.img

# Import UKI into ostree repo & create a new commit
RUN ostree container commit

# Sign ostree commit
RUN --mont=type=secret,id=key \
    ostree sign --keys-file /run/secrets/ostree ${commit} --repo=/ostree/repo
