#!/bin/bash
set -euo pipefail

# Making sure the context is right
#  - make sure we are root  
#  - enable fsverity on the root filesystem
#  - enabel fsverity on the ostree repository

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Pull containers ahead of time
skopeo copy docker://quay.io/travier/fedora-coreos-uki:latest oci-archive:coreos-signed
podman pull quay.io/travier/fedora-coreos-uki:uki

# Download scripts
git clone --depth=1 https://github.com/travier/fedora-coreos-uki setup 

